name: 📄 Documentation issue
description: Found an issue in the documentation? You can use this one!
title: "[Doc]: <Write a concise title here>"
body:
    - type: checkboxes
      id: no-duplicate-issues
      attributes:
          label: Is there an existing issue for this?
          description:
              Please search to see if an issue already exists for the issue you encountered.
          options:
              - label:
                    I have searched the existing
                    [issues](https://github.com/trvswgnr/sloth-pipe/issues)
                required: true
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to create this issue!
    - type: input
      id: contact
      attributes:
          label: Contact Details
          description: How can we get in touch with you if we need more info?
          placeholder: ex. email@example.com
      validations:
          required: false
    - type: textarea
      id: description
      attributes:
          label: Description
          description: Write a detailed description of the changes you are proposing.
      validations:
          required: true
    - type: input
      id: version
      attributes:
          label: Version
          description: What version of our package are you running?
          placeholder: ex. 0.0.7
      validations:
          required: false
    - type: dropdown
      id: browsers
      attributes:
          label: "What browsers are you seeing the problem on?"
          multiple: true
          options:
              - Chrome
              - Firefox
              - Safari
              - Microsoft Edge
              - Brave
              - Opera
              - Other
          default: 0
      validations:
          required: false
    - type: checkboxes
      id: willing-to-work
      attributes:
          label: "Are you willing to work on this issue?"
          options:
              - label: "Yes I am. (leave this unchecked for No)"
                required: false
